version: '3.8'
services:
  app:
    container_name: house_laravel
    build: .
    ports:
      - "8024:8024"
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Occihc72?
      MYSQL_DATABASE: housegreenyellow
      MYSQL_USER: rruffolo
      MYSQL_PASSWORD: Occihc72?
    ports:
      - "3307:3306"
